from app.core.llm import ask_llm
from app.core.state import AgentState
from app.tools.report_tools import create_report_pdf


def run_report_agent(
    state: AgentState,
    task: str,
) -> dict:
    """
    Generate a professional final report from the verified
    results collected during autonomous execution.
    """

    prompt = f"""
You are the Report Specialist Agent inside an autonomous
task-execution system.

Your responsibility is to turn the verified execution results
into a professional final report.

OVERALL GOAL:
{state.goal}

REPORT TASK:
{task}

EXECUTION HISTORY:
{state.history}

VERIFIED RESULTS:
{state.results}

Create a professional report containing only information
supported by the verified results.

Include, when applicable:

- Executive Summary
- Task Objective
- Dataset / Input Overview
- Actions Performed
- Data Quality Findings
- Machine Learning Approach
- Model Results
- Important Findings
- Interpretation
- Limitations and Risks
- Conclusions
- Recommendations
- Methodology

IMPORTANT RULES:

1. Do NOT invent values, metrics, observations, or results.
2. Clearly distinguish verified results from recommendations.
3. If information is unavailable, say that it was not available
   rather than making up an answer.
4. Use the actual model metrics returned by the tools.
5. Keep the report professional and readable.
6. Do not claim that a PDF could not be generated.
7. The PDF is generated by a separate Python tool after you
   produce the report content.
8. Do not include fake download links.
9. Do not mention limitations of the AI interface itself.
10. Focus on the actual task and its findings.

Return ONLY the report content in Markdown.
"""

    report_content = ask_llm(prompt)

    pdf_result = create_report_pdf(
        goal=state.goal,
        report_content=report_content,
        request_id=state.request_id,
        results=state.results,
    )

    result = {
        "report_content": report_content,
        "pdf": pdf_result,
    }

    state.add_action(
        agent="ReportAgent",
        action=task,
        result=result,
    )

    return result